<?php
namespace Tolerable\PayPal;

use \PHPUnit_Framework_TestCase;
use Guzzle\Service\Client;

/**
 * Test class for Tolerable_PayPal_Gateway.
 * Generated by PHPUnit on 2011-12-30 at 20:52:21.
 */
class GatewayTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Gateway
     */
    protected $gateway;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $httpClient = new Client();
        $httpClient->setConfig(array(
            'curl.CURLOPT_SSL_VERIFYHOST' => false,
            'curl.CURLOPT_SSL_VERIFYPEER' => false,
        ));
        $this->gateway = new Gateway(
                $httpClient, "seller_1298871127_biz_api1.philipbrown.id.au",
                "1298871136", "AyfC9oEHO-Ezj45ZrHIGKn0Gg-DhAou.YiHYRSS9JazujWP6UXIBOZ-5",
                Gateway::SANDBOX_WS_URL);
    }

    /**
     * @todo Implement testSetExpressCheckout().
     */
    public function testSetExpressCheckout()
    {
        $item = new Item;
        $item->setName('Test Product')
             ->setAmount(10)
             ->setTax(1)
             ->setDescription('Test Product')
             ->setQuantity(2);
        
        $request = new Request\SetExpressCheckoutRequest(
                'http://example.com/return',
                'http://example.com/cancel');
        $request->addItem($item);
        $response = $this->gateway->setExpressCheckout($request);
        
        $this->assertFalse($response->isError());
        $this->assertNotEmpty($response->getToken());
        
        var_dump($response);
    }

    /**
     * @todo Implement testDoExpressCheckoutPayment().
     */
    public function testDoExpressCheckoutPayment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
